### ISSUE TITLE
Better process icon support

### ISSUE THREAD

**Issue by pu-007** [adriankarlen/neobrutal-zebar#24]
![image](https://github.com/user-attachments/assets/cdc55117-1aac-48ae-b697-2d791e7891d7)
When an icon is not mapped, it will be empty. Is it possible to display a default icon or obtain the icon from the icon of the executable file?

**Comment by pu-007** [comment]
Just like this.

https://stackoverflow.com/questions/77692520/how-to-extract-an-icon-from-an-exe-file

**Comment by adriankarlen** [comment]
The link you provided is unfortunately not applicable for this, to get the icon the client is matching against the process/title of the window, glazewm does not provide us with any icon info per se.

The way it is currently setup it defaults to `ti-brand-${process-name}`. This is since a lot of popular apps have a matching brand icon and process name (eg. discord, spotify, firefox etc.). However I have been thinking about this some as well. And I think a nice default icon would be good.
